# Generated by Django 5.2.17 on 2026-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='loyalty_points_per_dh',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='salon',
            name='loyalty_reward_notes',
            field=models.TextField(blank=True),
        ),
    ]
